### ISSUE TITLE
Unknown feature `proc_macro_span_shrink`

### ISSUE THREAD

**Issue by cicilzx** [cch123/asm-cli-rust#10]
Hi, I'm tring to build to application, but it would trigger an error if I use `cargo build`, what should I do?

Bellow is the error message:
```
error[E0635]: unknown feature `proc_macro_span_shrink`
  --> /local/home/zixliu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.47/src/lib.rs:92:30
   |
92 |     feature(proc_macro_span, proc_macro_span_shrink)
   |                              ^^^^^^^^^^^^^^^^^^^^^^

   Compiling cmake v0.1.48
For more information about this error, try `rustc --explain E0635`.
error: could not compile `proc-macro2` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
```

**Comment by bjorn3** [comment]
Try `cargo update -p proc_macro2` and use latest nightly rustc or alternatively switch to stable rustc. proc_macro2 enables unstable features when it detects nightly but fails to verify the unstable features still exist on your nightly.

**Comment by cicilzx** [comment]
Thank you so much! It's working now!
